# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns each observation's cluster location based on the euclidean distance
#' between the observation and cluster centers.
#'
#' @param x a numeric matrix with observations.
#' @param centers a numeric matrix with observations with cluster's centers
#' coordinates.
#'
#' @return A list with the following components:
#' \item{clusters }{a vector indicating each point observation's cluster. }
#' \item{distance }{a vector with the distance from each
#' observation to its corresponding cluster center. }
#'
cluster_location <- function(x, centers) {
    .Call('_ktaucenters_cluster_location', PACKAGE = 'ktaucenters', x, centers)
}

#' Counts the number of observations per cluster
#'
#' @param cluster_location a vector with positive intergers containing each
#' point observation's cluster.
#' @param n_clusters total number of clusters
#'
#' @return
#' Vector with number of observations per cluster
#'
cluster_counter <- function(cluster_location, n_clusters) {
    .Call('_ktaucenters_cluster_counter', PACKAGE = 'ktaucenters', cluster_location, n_clusters)
}

#' Distance Matrix Computation
#'
#' Computes and returns the distance matrix using euclidean distance
#' measure to compute the distances between the rows of a
#' data matrix.
#'
#' @param x a numeric matrix.
#'
#' @return
#' A numeric matrix with the distances between the rows of a matrix.
#'
distance <- function(x) {
    .Call('_ktaucenters_distance', PACKAGE = 'ktaucenters', x)
}

#' Find the k Nearest Neighbors
#'
#' \strong{Ties}: If the kth and the (k+1)th nearest neighbor are tied, then
#' the neighbor found first is returned and the other one is ignored.
#'
#' @param D a distance matrix, which contains the distances between the rows of
#' a matrix.
#' @param k number of neighbors to find.
#'
#' @return A list with the following components:
#' \item{dist }{a matrix with distances. }
#' \item{id }{a matrix with indices of the k nearest neighbors. }
#' \item{k }{number neighbors used. }
#'
dist_to_kNN <- function(D, k) {
    .Call('_ktaucenters_dist_to_kNN', PACKAGE = 'ktaucenters', D, k)
}

#' Robust Clustering algorithm based on centers, a robust and efficient version
#' of kmeans.
#'
#' @param x numeric matrix of size n x p with all observations.
#' @param centers numeric matrix with initial cluster centers.
#' @param tolerance maximum difference between current and new computed
#' clusters. Parameter used for the algorithm stopping rule.
#' @param max_iter a maximum number of iterations used for the algorithm
#' stopping rule.
#'
#' @return A list with the following components:
#' \item{tau }{\eqn{\tau} scale value. }
#' \item{iter }{number of iterations until convergence is achieved or maximum
#' number of iteration is reached. }
#' \item{di }{distance of each observation to its nearest cluster center. }
#' \item{centers }{numeric matrix of size K x p, with the estimated K centers.
#'  }
#' \item{clusters }{integer vector of size n with the cluster location for each
#' observation. }
#' \item{p }{dimension where all observations live. }
#'
#'@references
#' [1] Gonzalez, J. D., Yohai, V. J., & Zamar, R. H. (2019).
#' Robust Clustering Using Tau-Scales. arXiv preprint arXiv:1906.08198.
#'
#' [2] Maronna, R. A. and Yohai, V. J. (2017). Robust and efficient estimation
#' of multivariate scatter and location.Computational Statistics &Data
#' Analysis, 109 : 64–75.
#'
ktaucenters_run <- function(x, centers, tolerance, max_iter) {
    .Call('_ktaucenters_ktaucenters_run', PACKAGE = 'ktaucenters', x, centers, tolerance, max_iter)
}

#' Flag outliers
#'
#' @param cutoff quantile of chi-square to be used as a threshold for outliers
#' detection.
#' @param b break down point.
#' @param ktau ktaucenters results.
#'
#' @return
#' Numeric vector with the weight factor for each observation
#'
flag_outliers <- function(cutoff, b, ktau) {
    .Call('_ktaucenters_flag_outliers', PACKAGE = 'ktaucenters', cutoff, b, ktau)
}

#' Quasi optimal \eqn{\rho} function
#'
#' @param x numeric vector with positive values.
#' @param c tunning constant.
#'
#' @return
#' Numeric vector with quasi optimal \eqn{\rho} computation for each element
#' of x.
#'
#'@references
#' [1] Salibian-Barrera, M., Willems, G., & Zamar, R. (2008). The fast-tau
#' estimator for regression. Journal of Computational and GraphicalStatistics,
#' 17(3), 659-682.
#'
#'@export
rhoOpt <- function(x, c) {
    .Call('_ktaucenters_rhoOpt', PACKAGE = 'ktaucenters', x, c)
}

#' Derivative of the quasi optimal \eqn{\rho} function
#'
#' @param x numeric vector with positive values.
#' @param c tunning constant.
#'
#' @return
#' Numeric vector with the derivative of the quasi optimal \eqn{\rho}
#' computation for each element of x.
#'
#'@export
psiOpt <- function(x, c) {
    .Call('_ktaucenters_psiOpt', PACKAGE = 'ktaucenters', x, c)
}

#' Second derivative of the quasi \eqn{\rho} function
#'
#' @param x numeric vector with positive values.
#' @param c tunning constant.
#'
#' @return
#' Numeric vector with the second derivative of the quasi optimal \eqn{\rho}
#' computation for each element of x.
#'
#'@export
derpsiOpt <- function(x, c) {
    .Call('_ktaucenters_derpsiOpt', PACKAGE = 'ktaucenters', x, c)
}

#' Estimates the local points density.
#'
#' @param D a distance matrix, which contains the distances between the rows of
#' a matrix.
#' @param k number of neighbors to calculate local point density.
#'
#' @return
#' A vector containing the density values for each point.
#'
point_density <- function(D, k) {
    .Call('_ktaucenters_point_density', PACKAGE = 'ktaucenters', D, k)
}

#' Utility function to estimate robinden center
#'
#' @param idp a vector with containing the inverse density each point.
#' @param indices vector with sorted indices.
#' @param crit_robin critical robin value.
#'
#' @return
#' Index of the cluster center
#'
robin_center <- function(idp, indices, crit_robin) {
    .Call('_ktaucenters_robin_center', PACKAGE = 'ktaucenters', idp, indices, crit_robin)
}

#' Robust Initialization based on Inverse Density estimator (ROBINDEN)
#'
#' Searches for k initial cluster seeds for k-means based clustering methods.
#'
#' @param D a distance matrix, which contains the distances between the rows of
#' a matrix.
#' @param n_clusters number of cluster centers to find.
#' @param mp number of nearest neighbors to compute point density
#'
#' @return A list with the following components:
#' \item{centers }{A numeric vector with the initial cluster centers indices}
#' \item{idpoints }{A real vector containing the inverse of point density
#' estimation}
#'
#' @details
#' The centers are the observations located in the most dense region
#' and far away from each other at the same time.
#' In order to find the observations in the highly dense region, this function
#' uses point density estimation (instead of Local Outlier Factor, Breunig et
#' al (2000)), see more details.
#'
#' @note This is a slightly modified version of ROBIN algorithm
#' implementation done by Sarka Brodinova <sarka.brodinova@tuwien.ac.at>.
#' @author Juan Domingo Gonzalez <juanrst@hotmail.com>
#'
#' @references Hasan AM, et al. Robust partitional clustering by
#' outlier and density insensitive seeding. Pattern Recognition Letters,
#' 30(11), 994-1002, 2009.
#'
#'@export
robinden <- function(D, n_clusters, mp) {
    .Call('_ktaucenters_robinden', PACKAGE = 'ktaucenters', D, n_clusters, mp)
}

#' Normal Consistency Constants
#'
#' M scale tuning constants so it is consistent with the standard
#' normal distribution for the quasi optimal \eqn{\rho} function used in
#' \code{\link{rhoOpt}}. These constants were computed for 1 \eqn{\leq} p
#' \eqn{\leq} 400.
#'
#' @param p dimension where observation lives.
#'
#' @return tuning constant.
#'
#' @references
#' [1] Maronna, R. A., Martin, R. D., Yohai, V. J., & Salibián-Barrera, M.
#' (2018). 'Robust statistics: theory and methods (with ' R). Wiley.
#'
#' [2] Salibian-Barrera, M., Willems, G., & Zamar, R. (2008). The fast-tau
#' estimator for regression. 'Journal of Computational and Graphical
#' Statistics, 17(3), 659-682.
#'
normal_consistency_constants <- function(p) {
    .Call('_ktaucenters_normal_consistency_constants', PACKAGE = 'ktaucenters', p)
}

#' Tuning constant for \eqn{\tau}-estimator
#'
#' Tuning constant approximation for \eqn{\tau}-estimator to reach 90%
#' efficiency
#'
#' @param p dimension where observation lives.
#'
#' @return
#' Tuning constant for \eqn{\tau}-estimator.
#'
#' @references
#' Maronna, R. A. and Yohai, V. J. (2017). Robust and efficient estimation of
#' multivariate scatter and location. Computational Statistics & Data Analysis,
#' 109:64–75.
#'
const_c2 <- function(p) {
    .Call('_ktaucenters_const_c2', PACKAGE = 'ktaucenters', p)
}

#' M scale
#'
#' The M scale of an univariate sample.
#'
#' @param u numeric vector with positive values.
#' @param c a tuning constant. If consistency to standard normal distribution
#' is desired use \code{\link{normal_consistency_constants}}
#' @param b the desired break down point.
#'
#' @return
#' M scale value
#'
mscale <- function(u, c, b) {
    .Call('_ktaucenters_mscale', PACKAGE = 'ktaucenters', u, c, b)
}

#' \eqn{\tau} scale
#'
#' The \eqn{\tau} scale of an univariate sample.
#'
#' @param u numeric vector with positive values.
#' @param s M scale for the same univariate sample (u).
#' @param c tuning constant to regulate estimator's efficiency.
#'
#' @return
#' \eqn{\tau} scale value
#'
tau_scale <- function(u, c, s) {
    .Call('_ktaucenters_tau_scale', PACKAGE = 'ktaucenters', u, c, s)
}

#' Weight function
#'
#' @param distances numeric vector with distances from each point to its
#' cluster center.
#' @param c1 tuning constant used for m scale estimation.
#' @param c2 tuning constant used for \eqn{\tau} scale estimation.
#' @param s M scale for the same vector of distances.
#'
#' @return
#' Numeric vector with the weight for each observation
#'
wni <- function(distances, c1, c2, s) {
    .Call('_ktaucenters_wni', PACKAGE = 'ktaucenters', distances, c1, c2, s)
}

#' Weight factor
#'
#' @param wni numeric vector with the weight for each observation.
#' @param clusters integer vector with the cluster location for each
#' observation.
#'
#' @return
#' Numeric vector with the weight factor for each observation
#'
weight_factor <- function(wni, clusters) {
    .Call('_ktaucenters_weight_factor', PACKAGE = 'ktaucenters', wni, clusters)
}

#' Computes new cluster centers
#'
#' @param x numeric matrix of size n x p with all observations.
#' @param weights numeric vector of size n with the weight factor for each
#' observation.
#' @param cluster_location integer vector of size n with the cluster location
#' for each observation.
#' @param n_clusters integer vector of size n with the
#' cluster location for each ' observation.
#' @param distances numeric vector of size n with the distances from each
#' observation to its nearest cluster center.
#'
#' @return
#' Numeric matrix with the new cluster centers.
#'
new_centers <- function(x, weights, cluster_location, n_clusters, distances) {
    .Call('_ktaucenters_new_centers', PACKAGE = 'ktaucenters', x, weights, cluster_location, n_clusters, distances)
}

#' Computes the median of a numeric vector
#'
#' @param x numeric vector.
#'
#' @return median of a numeric vector.
#'
median_cpp <- function(x) {
    .Call('_ktaucenters_median_cpp', PACKAGE = 'ktaucenters', x)
}

#' Find the first nth indices from a vector
#'
#' @param v a numeric vector from which indices are found.
#' @param n number of indices to find.
#' @param decreasing boolean value indicating if the vector must be in
#' decreasing order
#'
#' @return
#' A vector with first nth indices.
#'
top_index <- function(v, n, decreasing) {
    .Call('_ktaucenters_top_index', PACKAGE = 'ktaucenters', v, n, decreasing)
}

#' Estimates maximum tolerance between two given matrix row wise
#'
#' @param x numeric matrix.
#' @param y numeric matrix.
#'
#' @return max euclidean difference two given matrix row wise.
#'
max_tolerance <- function(x, y) {
    .Call('_ktaucenters_max_tolerance', PACKAGE = 'ktaucenters', x, y)
}

